# Generated by Django 6.0.3 on 2026-05-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportedGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pgn", models.TextField()),
                ("white", models.CharField(blank=True, max_length=100)),
                ("black", models.CharField(blank=True, max_length=100)),
                ("event", models.CharField(blank=True, max_length=200)),
                ("date", models.CharField(blank=True, max_length=20)),
                ("result", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
